=== danganhphu/QuanLyNhanVien_XML/QuanLyNhanVien/DuLieu/congty.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="congty">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nhanvien">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hoten" type="xs:string"/>
                            <xs:element name="luong" type="xs:nonNegativeInteger"/>
                            <xs:element name="phongban">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tenphong" type="xs:string"/>
                                        <xs:element name="dienthoai">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                  <xs:pattern value="[0-9]{10,10}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="manv">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[N,V]{2}[0-9]{2}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="MaNVKey">
            <xs:selector xpath="NhanVien"/>
            <xs:field xpath="manv"/>
        </xs:key>
    </xs:element>
</xs:schema>

=== danganhphu/QuanLyNhanVien_XML/QuanLyNhanVien/DuLieu/congty.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="congty.xsl"?>

<congty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="congty.xsd">
	<nhanvien manv="NV01">
		<hoten>Đặng Anh Phú</hoten>
		<luong>12700</luong>
		<phongban>
			<tenphong>Hành chính</tenphong>
			<dienthoai>0986218211</dienthoai>
		</phongban>
	</nhanvien>

	<nhanvien manv="NV02">
		<hoten>Phan Hồng Nam</hoten>
		<luong>8000</luong>
		<phongban>
			<tenphong>Nhân sự</tenphong>
			<dienthoai>0986216457</dienthoai>
		</phongban>
	</nhanvien>

	<nhanvien manv="NV03">
		<hoten>Nguyễn Thị Hồng</hoten>
		<luong>1921</luong>
		<phongban>
			<tenphong>Tai chinh</tenphong>
			<dienthoai>0938312124</dienthoai>
		</phongban>
	</nhanvien>
</congty>
