=== danganhphu/QuanLyNhanVien_XML/QuanLyNhanVien/Data/congty.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="congty">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nhanvien" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hoten" type="xs:string"/>
                            <xs:element name="luong" type="xs:nonNegativeInteger"/>
                            <xs:element name="phongban">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tenphong" type="xs:string"/>
                                        <xs:element name="dienthoai">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                  <xs:pattern value="[0-9]{10,10}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="manv">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[N,V]{2}[0-9]{2}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>


                <xs:element name="HopDongLD" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TenHD" type="xs:string"/>
                            <xs:element name="NgayBD" type="xs:date"/>
                            <xs:element name="NgayKT" type="xs:date"/>
                        </xs:sequence>
                        <xs:attribute name="MaHD">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[H,D]{2}[0-9]{2}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="manv">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[N,V]{2}[0-9]{2}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="MaNVKey">
            <xs:selector xpath="NhanVien"/>
            <xs:field xpath="@manv"/>
        </xs:key>
        <xs:key name="HDLDKey">
            <xs:selector xpath="HopDongLD"/>
            <xs:field xpath="@MaHD"/>
            <xs:field xpath="@manv"/>
        </xs:key>
        <xs:keyref name="HDLD_NVKeyref" refer="MaNVKey">
            <xs:selector xpath="HopDongLD"/>
            <xs:field xpath="@manv"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== danganhphu/QuanLyNhanVien_XML/QuanLyNhanVien/Data/congty.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="congty.xsl"?>
<congty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="congty.xsd">
	<nhanvien manv="NV01">
		<hoten>Đặng Anh Phú</hoten>
		<luong>8000</luong>
		<phongban>
			<tenphong>Nhập sách</tenphong>
			<dienthoai>0986218211</dienthoai>
		</phongban>
	</nhanvien>
	<nhanvien manv="NV02">
		<hoten>Phan Hồng Nam</hoten>
		<luong>900</luong>
		<phongban>
			<tenphong>Thủ thư</tenphong>
			<dienthoai>0986216457</dienthoai>
		</phongban>
	</nhanvien>
	<nhanvien manv="NV03">
		<hoten>Nguyen Van Hai</hoten>
		<luong>1221</luong>
		<phongban>
			<tenphong>Kế toán</tenphong>
			<dienthoai>0938312124</dienthoai>
		</phongban>
	</nhanvien>
	<nhanvien manv="NV04">
		<hoten>Bùi Văn Tình</hoten>
		<luong>3242</luong>
		<phongban>
			<tenphong>Marketing</tenphong>
			<dienthoai>0938423456</dienthoai>
		</phongban>
	</nhanvien>
	<nhanvien manv="NV05">
		<hoten>Lê Thúy Kiều</hoten>
		<luong>6503</luong>
		<phongban>
			<tenphong>Thủ thư</tenphong>
			<dienthoai>0876025046</dienthoai>
		</phongban>
	</nhanvien>
	<nhanvien manv="NV06">
		<hoten>Trần Văn Nam</hoten>
		<luong>5400</luong>
		<phongban>
			<tenphong>Nhập sách</tenphong>
			<dienthoai>0864178742</dienthoai>
		</phongban>
	</nhanvien>
	<nhanvien manv="NV07">
		<hoten>Nguyễn Hữu Vương</hoten>
		<luong>5700</luong>
		<phongban>
			<tenphong>Thủ Thư</tenphong>
			<dienthoai>0347489215</dienthoai>
		</phongban>
	</nhanvien>
	<HopDongLD MaHD="HD01" manv="NV01">
		<TenHD>Hợp đồng lao động viết tay</TenHD>
		<NgayBD>2022-05-20</NgayBD>
		<NgayKT>2023-05-20</NgayKT>
	</HopDongLD>
	<HopDongLD MaHD="HD02" manv="NV02">
		<TenHD>Hợp đồng hứa hẹn bằng lời nói và viết tay</TenHD>
		<NgayBD>2022-05-10</NgayBD>
		<NgayKT>2022-10-10</NgayKT>
	</HopDongLD>
	<HopDongLD MaHD="HD03" manv="NV03">
		<TenHD>Hợp đồng bằng miệng</TenHD>
		<NgayBD>2022-04-15</NgayBD>
		<NgayKT>2023-10-15</NgayKT>
	</HopDongLD>
	<HopDongLD MaHD="HD04" manv="NV04">
		<TenHD>Hợp đồng bằng miệng</TenHD>
		<NgayBD>2022-03-02</NgayBD>
		<NgayKT>2022-06-30</NgayKT>
	</HopDongLD>
	<HopDongLD MaHD="HD05" manv="NV05">
		<TenHD>Hợp đồng lao động viết tay</TenHD>
		<NgayBD>2021-02-09</NgayBD>
		<NgayKT>2022-11-09</NgayKT>
	</HopDongLD>
</congty>
